### ISSUE TITLE
SQLite pushed hard 

### ISSUE THREAD

**Issue by gedw99** [pocketbase/benchmarks#1]
https://www.terlici.com/2023/11/06/pushing-sqlite-limits.html Shows sone good benchmarks

sqlite and golang 

24K requests per second, 72Mbit/s traffic, 271MB RAM used. That’s with writes concurrently

am think it might be good to change the benchmarks to writes / second styje results because that is how users would want to do the metrics on their servers. Then we can start to see comparative results .

**Comment by ganigeorgiev** [comment]
Thanks for sharing. Benchmarking PocketBase applications is a little more complicated vs raw SQLite as there multiple layers before between the request and the database (routing middlewares, collection API rules, validations, json response filtering, etc.).

For the most recent PocketBase benchmarks you can explore the [Results files](https://github.com/pocketbase/benchmarks#results).

**Comment by ganigeorgiev** [comment]
> I assume conc: 500 means that its 500 concurrent users ?

Yes.

But again the linked benchmark cannot be compared directly to PocketBase because we do a lot more work. You are not taking in consideration:

- route handling and middlewares (even a simple middleware function call can have drastic impact on micro benchamarks)
- activity logger (aka. db request log writes)
- data validations
- data serialization
- hook calls
- the benchmark test runs as part of the same application process that started the PocketBase server
- pure Go (PocketBase default) vs CGO SQLite drivers (which the article uses; the linked article also uses prepared statements)
- difference in the running hardware
- connection limits to avoid starving the file descriptors and memory - we have [default limits](https://github.com/pocketbase/pocketbase/blob/985ab1e5b79a328b516decca3d1d7dc8edfcbba0/core/base.go#L28) to the max open and idle connections
- PocketBase maintain separate read and write pools + have auto fail-retry handling to take care for the `SQLITE_BUSY` errors
- and probably other...
